# spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-vue-admin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456


# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml

# tomcat
server:
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9897
  servlet:
    context-path: /
